#
# Module manifest for module 'GCCare' [Garmin Connect Care]
# Generated by: zimmermann.holger@live.de
# Generated on: 2026
#

@{
    PrivateData       = @{
        PSData = @{
            LastUpdate = '2026-10-03'
            Tags         = @('Garmin', 'GarminConnect', 'PowerShell', 'PowerShellModule', 'FIT', 'TCX', 'Health', 'Fitness', 'BodyComposition', 'GarminConnectCare')
            ProjectUri   = 'https://github.com/HerrHozi/GCCare'
            LicenseUri   = 'https://github.com/HerrHozi/GCCare/blob/main/LICENSE'
            ReleaseNotes = '            

2026.6.1.1089
        - Added & improved Function: 
        - Add-GarminBodyComposition
        - Get-GarminBadge
        - Get-GarminActivity

- Version 2026.10.2.714
        - Replaced all Python Functions by PowerShell

2026.8.19.925
        - Added Function Invoke-PipInstall.ps1

2026.8.18.1071
        - Added Functions Test-GCCarePythonInstalled.ps1 & Test-GCCarePipPackageInstalled.ps1

2026.6.9.954
        - Updated Function Convert-SecToMin

2026.6.4.614
        - Updated Help Info & Readme file

2026.6.1.1089
        - Added Function Convert-TanitaExportToFitFile
        - Added Function Send-FitFileToGarminConnect

2026.6.1.823
        - Added Function Update-TCXFile

2026.5.22.1018
        - First Version' 
        }
    } 
 
    

    RootModule        = 'GCCare.psm1'
    ModuleVersion = '2026.10.3.686'
    GUID              = '18240772-2f3d-408e-be7e-bc1ca3d407d9'

    Author            = 'Holger Zimmermann | zimmermann.holger@live.de'
    CompanyName       = 'Community'
    Copyright         = 'License: MIT | Copyright (c) 2026 Holger Zimmermann'

    Description       = 'GCCare is an acronym for Garmin Connect Care.'

    PowerShellVersion = '7.1'
    FunctionsToExport = '*'
    AliasesToExport   = '*'
    VariablesToExport = '*'
    HelpInfoURI       = 'https://herrhozi.com/'
}

