#
# Module manifest for module 'GCCare' [Garmin Connect Care]
# Generated by: zimmermann.holger@live.de
# Generated on: 2026
#

@{
    PrivateData       = @{
        PSData = @{
            LastUpdate   = '2026-08-19'
            Tags         = @('Garmin', 'GarminConnect', 'PowerShell', 'PowerShellModule', 'FIT', 'TCX', 'Health', 'Fitness', 'BodyComposition', 'GarminConnectCare')
            ProjectUri   = 'https://github.com/HerrHozi/GCCare'
            LicenseUri   = 'https://github.com/HerrHozi/GCCare/blob/main/LICENSE'
            ReleaseNotes = '            

2026.5.21.957
        - Added Golden Ticket Attack to Phase 12 Domain Persistence.

2026.5.18.1200
        - Added GPO Template modification to Phase 12 Domain Persistence.

v2026.5.7.1034 
		- Privileged Escalation via ESC1 added. 
        - Minor bug fixes and performance improvements.
        
2026.3.17.1034 
		- Initial release of GCCare on PS Gallery.' 
        }
    } 
 
    

    RootModule        = 'GCCare.psm1'
    ModuleVersion     = '2026.8.19.925'
    GUID              = '18240772-2f3d-408e-be7e-bc1ca3d407d9'

    Author            = 'Holger Zimmermann | zimmermann.holger@live.de'
    CompanyName       = 'Community'
    Copyright         = 'License: MIT | Copyright (c) 2026 Holger Zimmermann'

    Description       = 'GCCare is an acronym for Garmin Connect Care.'

    PowerShellVersion = '7.1'
    FunctionsToExport = '*'
    AliasesToExport   = '*'
    VariablesToExport = '*'
    HelpInfoURI       = 'https://herrhozi.com/'
}

